# Generated by Django 4.2.2 on 2024-09-18 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('numero_cuenta', models.CharField(max_length=20, unique=True)),
                ('total_dinero', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prestamos', models.IntegerField(default=0)),
                ('deuda', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='PagoMensualidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.socio')),
            ],
        ),
    ]
