# Generated by Django 4.2.2 on 2024-09-20 02:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_prestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagomensualidad',
            name='mes',
            field=models.CharField(default='Enero', max_length=20),
        ),
        migrations.AlterField(
            model_name='pagomensualidad',
            name='fecha_pago',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
