# Generated by Django 4.2.2 on 2024-09-23 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0004_prestamo_interes_prestamo_meses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuotaPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.IntegerField()),
                ('monto_cuota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interes_cuota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_restante', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagada', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.prestamo')),
            ],
        ),
    ]
