# Generated by Django 4.2.2 on 2024-09-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0005_cuotaprestamo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=20)),
                ('ingresos_totales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('egresos_totales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
